# Generated by Django 5.2.17 on 2026-10-03 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0001_initial'),
        ('portfolio', '0002_partnercredit_servicepage_category_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='inquiries', to='portfolio.photo'),
        ),
    ]
