# Generated by Django 5.2.17 on 2026-10-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0002_inquiry_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='service',
            field=models.CharField(blank=True, choices=[('athlete-portraits', 'Individual athlete portraits'), ('team-photos', 'Team and group photos'), ('sports-action', 'Game-day action and training'), ('race-events', 'Races and endurance events'), ('sports-events', 'Tournaments and sporting events'), ('fitness-promotion', 'Fitness and sports promotion')], max_length=40),
        ),
    ]
