# Generated by Django 5.2.17 on 2026-10-03 01:01

import django.core.validators
import django.db.models.deletion
import portfolio.models
import portfolio.storage
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name_en', models.CharField(max_length=80)),
                ('name_fr', models.CharField(blank=True, max_length=80)),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('source', models.FileField(storage=portfolio.storage.original_storage, upload_to=portfolio.models.source_path)),
                ('source_url', models.URLField(blank=True)),
                ('flickr_id', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('title_en', models.CharField(max_length=160)),
                ('title_fr', models.CharField(blank=True, max_length=160)),
                ('caption_en', models.TextField(blank=True)),
                ('caption_fr', models.TextField(blank=True)),
                ('alt_en', models.CharField(max_length=300)),
                ('alt_fr', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('featured', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=12)),
                ('focal_x', models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MaxValueValidator(100)])),
                ('focal_y', models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MaxValueValidator(100)])),
                ('width', models.PositiveIntegerField(default=0, editable=False)),
                ('height', models.PositiveIntegerField(default=0, editable=False)),
                ('credit', models.CharField(default='MrSaintJ Photography', max_length=120)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', editable=False, max_length=12)),
                ('processing_error', models.TextField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='photos', to='portfolio.category')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='cover_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_covers', to='portfolio.photo'),
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton', models.PositiveSmallIntegerField(default=1, editable=False, unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1)])),
                ('brand', models.CharField(default='MrSaintJ Photography', max_length=100)),
                ('photographer_name', models.CharField(default='Justin St-Laurent', max_length=100)),
                ('location', models.CharField(default='Montréal · Québec', max_length=120)),
                ('hero_heading_en', models.CharField(default='Effort.\nIn focus.', help_text='Separate the two lines with a newline.', max_length=100)),
                ('hero_heading_fr', models.CharField(default="L'effort.\nEn image.", max_length=100)),
                ('tagline_en', models.CharField(default='The action. The people. The whole event.', max_length=160)),
                ('tagline_fr', models.CharField(default="L'action. Les gens. L'événement.", max_length=160)),
                ('biography_en', models.TextField(blank=True)),
                ('biography_fr', models.TextField(blank=True)),
                ('approach_en', models.TextField(blank=True)),
                ('approach_fr', models.TextField(blank=True)),
                ('contact_intro_en', models.TextField(blank=True)),
                ('contact_intro_fr', models.TextField(blank=True)),
                ('flickr_url', models.URLField(default='https://www.flickr.com/photos/194206904@N02/albums/72177720309211783/')),
                ('instagram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('public_email', models.EmailField(blank=True, max_length=254)),
                ('cv', models.FileField(blank=True, upload_to='cv/')),
                ('hero_focal_x', models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MaxValueValidator(100)])),
                ('hero_focal_y', models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MaxValueValidator(100)])),
                ('mobile_focal_x', models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MaxValueValidator(100)])),
                ('mobile_focal_y', models.PositiveSmallIntegerField(default=38, validators=[django.core.validators.MaxValueValidator(100)])),
                ('hero_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desktop_heroes', to='portfolio.photo')),
                ('mobile_hero_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobile_heroes', to='portfolio.photo')),
            ],
            options={
                'verbose_name_plural': 'site settings',
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title_en', models.CharField(max_length=160)),
                ('title_fr', models.CharField(blank=True, max_length=160)),
                ('introduction_en', models.TextField()),
                ('introduction_fr', models.TextField(blank=True)),
                ('body_en', models.TextField(blank=True)),
                ('body_fr', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('collection', 'Collection'), ('event', 'Event story')], default='collection', max_length=12)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('assignment_en', models.TextField(blank=True)),
                ('assignment_fr', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=12)),
                ('cover_photo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='covered_stories', to='portfolio.photo')),
            ],
            options={
                'verbose_name_plural': 'stories',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='StoryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('caption_en', models.TextField(blank=True)),
                ('caption_fr', models.TextField(blank=True)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.photo')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequence', to='portfolio.story')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='story',
            name='photos',
            field=models.ManyToManyField(related_name='stories', through='portfolio.StoryPhoto', to='portfolio.photo'),
        ),
        migrations.CreateModel(
            name='PhotoRendition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='photos/')),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('format', models.CharField(choices=[('webp', 'WebP'), ('jpeg', 'JPEG')], max_length=8)),
                ('byte_size', models.PositiveIntegerField()),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renditions', to='portfolio.photo')),
            ],
            options={
                'ordering': ['width'],
                'constraints': [models.UniqueConstraint(fields=('photo', 'width', 'format'), name='unique_photo_rendition')],
            },
        ),
        migrations.AddConstraint(
            model_name='storyphoto',
            constraint=models.UniqueConstraint(fields=('story', 'photo'), name='unique_story_photo'),
        ),
    ]
