# Generated by Django 5.2.17 on 2026-10-03 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100, unique=True)),
                ('url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=False, help_text='Company credits are hidden unless explicitly enabled.')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ServicePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('slug_en', models.SlugField(unique=True)),
                ('slug_fr', models.SlugField(blank=True)),
                ('title_en', models.CharField(max_length=160)),
                ('title_fr', models.CharField(blank=True, max_length=160)),
                ('introduction_en', models.TextField()),
                ('introduction_fr', models.TextField(blank=True)),
                ('body_en', models.TextField(blank=True)),
                ('body_fr', models.TextField(blank=True)),
                ('coverage_en', models.TextField(blank=True, help_text='One coverage topic per line.')),
                ('coverage_fr', models.TextField(blank=True)),
                ('seo_title_en', models.CharField(blank=True, max_length=160)),
                ('seo_title_fr', models.CharField(blank=True, max_length=160)),
                ('seo_description_en', models.CharField(blank=True, max_length=300)),
                ('seo_description_fr', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='behind_frame_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='behind_frame_fr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='story',
            name='behind_frame_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='story',
            name='behind_frame_fr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='story',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='storyphoto',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='ServiceFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_en', models.CharField(max_length=200)),
                ('question_fr', models.CharField(blank=True, max_length=200)),
                ('answer_en', models.TextField()),
                ('answer_fr', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='portfolio.servicepage')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ServicePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.photo')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_sequence', to='portfolio.servicepage')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='servicepage',
            name='photos',
            field=models.ManyToManyField(related_name='services', through='portfolio.ServicePhoto', to='portfolio.photo'),
        ),
        migrations.CreateModel(
            name='ServiceSlugRedirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'Français')], max_length=2)),
                ('slug', models.SlugField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.servicepage')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_sequence', to='portfolio.servicepage')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.story')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='servicepage',
            name='stories',
            field=models.ManyToManyField(related_name='services', through='portfolio.ServiceStory', to='portfolio.story'),
        ),
        migrations.AddConstraint(
            model_name='servicephoto',
            constraint=models.UniqueConstraint(fields=('service', 'photo'), name='unique_service_photo'),
        ),
        migrations.AddConstraint(
            model_name='serviceslugredirect',
            constraint=models.UniqueConstraint(fields=('language', 'slug'), name='unique_service_redirect'),
        ),
        migrations.AddConstraint(
            model_name='servicestory',
            constraint=models.UniqueConstraint(fields=('service', 'story'), name='unique_service_story'),
        ),
        migrations.AddConstraint(
            model_name='servicepage',
            constraint=models.UniqueConstraint(condition=models.Q(('slug_fr', ''), _negated=True), fields=('slug_fr',), name='unique_french_service_slug'),
        ),
    ]
