# Generated by Django 5.2.17 on 2026-10-03 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_partnercredit_servicepage_category_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorySlugRedirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.story')),
            ],
        ),
    ]
