# Generated by Django 5.2.17 on 2026-10-03 12:41

from django.db import migrations, models


def seed_publication_times(apps, schema_editor):
    for name in ("Photo", "Story", "ServicePage"):
        apps.get_model("portfolio", name).objects.using(schema_editor.connection.alias).filter(status="published").update(
            publication_changed_at=models.F("updated_at"))


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_storyslugredirect'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='publication_changed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='publication_changed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='publication_changed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.RunPython(seed_publication_times, migrations.RunPython.noop),
    ]
