# Generated by Django 5.2.17 on 2026-10-03 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_photo_publication_changed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='services_cover_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_index_covers', to='portfolio.photo'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='services_heading_en',
            field=models.CharField(default='Sports photography for athletes, teams & events', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='services_heading_fr',
            field=models.CharField(blank=True, default='Photographie sportive pour athlètes, équipes et événements', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='services_intro_en',
            field=models.TextField(default="From individual athlete portraits and team photos to game-day action, races, tournaments, and fitness sessions, I create images that capture the effort, energy, and people behind the sport. Based in Longueuil on Montréal's South Shore, I work with athletes, teams, clubs, and event organizers to plan photography around what matters most to them."),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='services_intro_fr',
            field=models.TextField(blank=True, default="Des portraits d'athlètes aux photos d'équipe, en passant par l'action en compétition, les courses, les tournois et les séances d'entraînement, je crée des images qui racontent l'effort, l'énergie et les personnes derrière le sport. Basé à Longueuil, sur la Rive-Sud de Montréal, je travaille avec les athlètes, les équipes, les clubs et les organisateurs pour adapter la couverture photo à leurs besoins."),
        ),
        migrations.CreateModel(
            name='ServiceOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('athlete-portraits', 'Individual athlete portraits'), ('team-photos', 'Team and group photos'), ('sports-action', 'Game-day action and training'), ('race-events', 'Races and endurance events'), ('sports-events', 'Tournaments and sporting events'), ('fitness-promotion', 'Fitness and sports promotion')], max_length=40, unique=True)),
                ('title_en', models.CharField(max_length=160)),
                ('title_fr', models.CharField(blank=True, max_length=160)),
                ('description_en', models.TextField()),
                ('description_fr', models.TextField(blank=True)),
                ('inquiry_label_en', models.CharField(max_length=120)),
                ('inquiry_label_fr', models.CharField(blank=True, max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publication_changed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('cover_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offering_covers', to='portfolio.photo')),
                ('detail_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offerings', to='portfolio.servicepage')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
    ]
