# Generated by Django 5.2.17 on 2026-10-04 15:54

import portfolio.models
import portfolio.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_sitesettings_services_cover_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='source',
            field=models.FileField(max_length=512, storage=portfolio.storage.original_storage, upload_to=portfolio.models.source_path),
        ),
        migrations.AlterField(
            model_name='photorendition',
            name='file',
            field=models.FileField(max_length=512, upload_to='photos/'),
        ),
    ]
